[package]
name = "redox"
version = "0.1.0"
edition = "2024"

[dependencies]
syn = { version = "2.0", features = ["full", "visit", "extra-traits"] }
proc-macro2 = "1.0"
quote = "1.0"
clap = { version = "4.5", features = ["derive"] }

[dev-dependencies]
tempfile = "3.0"
